[package]
name = "backflip"
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
edition = "2021"
description = "Help your Flipper Zero perform tricks!"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
color-eyre = "0.6.2"
nom = "7.1"
